import ThemeRegistry from "@/mui/ThemeRegistry/ThemeRegistry";
import "./globals.css";
import { Inter } from "next/font/google";
import HeadBar from "@/components/HeadBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <HeadBar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
